---
language: python
python: 2.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - "ansible-playbook -i tests/inventory tests/main.yml --syntax-check"

  - "ansible-playbook -i tests/inventory tests/main.yml --connection=local"

  - >
    ansible-playbook -i tests/inventory tests/main.yml --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
